---
# defaults file for docker

update_docker: no

docker_channel: stable

ubuntu_key_url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
apt_key_sig: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

system_arc: amd64
apt_repo: "deb [arch={{ system_arc }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} {{ docker_channel }}"
