---
- hosts: all

  become: yes
  become_method: sudo

  vars:
    docker_group_users: ubuntu
    cloud_server_protocol: http://
    cloud_server_domain: ec2-18-185-40-145.eu-central-1.compute.amazonaws.com
    github_clone_path: /home/ubuntu

  roles:
    - docker
    - nginx
    - setup_docker
