---
- hosts: all

  become: yes
  become_method: sudo

  vars:
    docker_group_users: ubuntu
    cloud_server_domain: http://ec2-18-185-40-145.eu-central-1.compute.amazonaws.com/

  roles:
    - docker
    - nginx

  tasks:
    - name: Clone lieblingsladen git
      git:
        repo: "https://github.com/maximilian-skowron/lieblingsladen.git"
        dest: "/home/ubuntu/lieblingsladen"
        recursive: yes
        update: yes
